_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 33
                - 40
                - 49
                - 51
                - 55
            "2":
                - 1
                - 33
                - 40
                - 49
                - 51
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": darwin-arm64
epochs:
    value: 10
